resolve 102 - magic
yegorf1/RogueBot pull request #162
Opened 2016-09-18 07:06 UTC by Encamy

Часть оставил так как было (user.set_room_temp не стал добавлять)

2016-09-18 13:41 UTC, Teogor commented
попробуй запустить собственного тест бота. так довольно легко найдешь ошибку

2016-09-18 14:46 UTC, Encamy commented
Да в том то и дело, я запускал, тестировал, все прекрасно работает. Не могу понять где ошибка

2016-09-18 14:48 UTC, thekiba commented
Запусти тесты `python3 ./tests.py`

2016-09-18 18:15 UTC, yegorf1 commented on items/good/scroll_superpower.py
> +		return stats_defenition.get_damage(user)*3
cho

2016-09-18 18:16 UTC, yegorf1 commented on items/good/scroll_thunderbolt.py
> +	if user.mp < 50:
Используй `User.use_mana`

2016-09-18 18:16 UTC, yegorf1 commented on items/good/scroll_thunderbolt.py
> +	damage_non_wet = round((stats_defenition.get_damage(user) + user.mana_damage)/2)*1.5 + 600
В питоне есть оператор `//`

2016-09-18 18:17 UTC, yegorf1 commented on items/good/scroll_superpower.py
> +		return stats_defenition.get_damage(user)*3
Используй user.get_damage()

2016-09-18 18:17 UTC, yegorf1 commented on items/bad/scroll_stone.py
> +name = 'Свиток вызова камней(100mp)'
Не пиши в названиях сколько стоит свиток
Лучше в описаниях, а лучше вообще не писать

2016-09-18 18:22 UTC, YogurtTheHorse requested changes

2016-09-20 07:56 UTC, kaldai commented on items/bad/scroll_stone.py
> +	'Все что о нем известно, так это то что на нем нарисован камень'
'Все что о нем известно, так это то, что на нем нарисован камень'

2016-09-20 07:57 UTC, kaldai commented on items/good/scroll_superpower.py
> +		reply('Твои руки увеличиваются и ты со всей силы бьешь врагу в лицо!')
'Твои руки увеличиваются, и ты со всей силы бьешь врагу в лицо!'

2016-09-20 07:59 UTC, kaldai commented on items/bad/scroll_stone.py
> +		reply('С неба падают камни прямо на тебя и наносят 50 урона')
'С неба падают камни прямо на тебя и наносят 50 урона.'

2016-09-20 07:59 UTC, kaldai commented on items/good/scroll_armor.py
> +	'Свиток железный, его не согнуть'
'Свиток железный, его не согнуть.'

2016-09-20 07:59 UTC, kaldai commented on items/good/scroll_armor.py
> +			reply('Ты читаешь заклинание и твои руки начинают трястись.\nТы не в состоянии их больше сдерживать\nОни начинают описывать круги. Твоя броня увеличилась на 1000 очков')
'Ты читаешь заклинание и твои руки начинают трястись.\nТы не в состоянии их больше сдерживать.\nОни начинают описывать круги. Твоя броня увеличилась на 1000 очков.'

2016-09-20 08:00 UTC, kaldai commented on items/good/scroll_armor.py
> +		reply('Ты уже использовал это заклинание')
'Ты уже использовал это заклинание.'

2016-09-20 08:00 UTC, kaldai commented on items/good/scroll_superpower.py
> +	'Только лишь взглянув на него, твои мускулы увеличились. Ты хочешь кого-то ударить'
'Только лишь взглянув на него, твои мускулы увеличились. Ты хочешь кого-то ударить.'

2016-09-20 08:00 UTC, kaldai commented on items/good/scroll_thunderbolt.py
> +	'На свитке нарисована молния\nКажется пахнет чем-то паленым'
'На свитке нарисована молния.\nКажется пахнет чем-то паленым.'

2016-09-20 08:01 UTC, kaldai commented on items/good/scroll_thunderbolt.py
> +		reply('Твои руки светятся\nТы чувствуешь как по ним пробегают разряды электричества')
'Твои руки светятся.\nТы чувствуешь, как по ним пробегают разряды электричества.'

2016-09-20 08:02 UTC, kaldai commented on items/good/scroll_thunderbolt.py
> +			reply('Выходя из твоего тела, молния перекинулась на влажное тело и ударила тебя током')
'Выходя из твоего тела, молния перекинулась на влажное тело и ударила тебя током.'

2016-09-20 08:02 UTC, kaldai commented on items/good/scroll_thunderbolt.py
> +			reply('Смочить врага водой было хорошей идеей')
'Смочить врага водой было хорошей идеей.'

2016-09-20 08:02 UTC, kaldai commented on items/good/scroll_water.py
> +	'Свиток мокрый\nТы попробовал его выжать, но он снова стал мокрым'
'Свиток мокрый.\nТы попробовал его выжать, но он снова стал мокрым.'

2016-09-20 08:03 UTC, kaldai commented on items/good/scroll_water.py
> +			reply('К сожалению на брызги разлетелись во все стороны и ты тоже стал мокрым')
'К сожалению, на брызги разлетелись во все стороны и ты тоже стал мокрым'

2016-09-20 17:29 UTC, closed without merging

2016-09-20 17:33 UTC, thekiba commented
@Encamy 
А зачем pull-request удалять?