Feature/#102 all fixes
yegorf1/RogueBot pull request #207
Opened 2016-09-20 18:16 UTC by Encamy

2016-09-21 14:27 UTC, yegorf1 commented on items/bad/scroll_stone.py
> +		if user.hp <= 0:
Проверять не нужно.

2016-09-21 14:27 UTC, yegorf1 commented on items/bad/scroll_stone.py
> +	if user.mp >= 100:
`user.use_mana()`

2016-09-21 14:27 UTC, YogurtTheHorse requested changes

2016-09-22 19:16 UTC, YogurtTheHorse commented on items/bad/scroll_stone.py
> +		if user.hp <= 0:
Эта проверка не нужна, игра сама все сделает

2016-09-22 19:18 UTC, Encamy commented on items/bad/scroll_stone.py
> +		if user.hp <= 0:
То есть можно вообще убрать?
`if user.hp <= 0:
			user.death(reply, reason='Камнепад')`

2016-09-22 19:38 UTC, yegorf1 commented on items/bad/scroll_stone.py
> +		if user.hp <= 0:
Да

2016-09-23 14:29 UTC, thekiba approved these changes

2016-09-23 14:33 UTC, merged