Part of vietnam DLC
yegorf1/RogueBot pull request #254
Opened 2016-09-26 22:32 UTC by daemonica

Issues #240, #241, #242, #243, #244, #245, #246

2016-09-27 01:26 UTC, daemonica commented
Не доделано. Надо как минимум продумать лут с хиппи.

2016-09-27 06:53 UTC, YogurtTheHorse requested changes
Весь лут перенести в items/loot

2016-09-27 06:53 UTC, yegorf1 commented on items/vietnam/ak.py
> +    'Исполняет русский рэп, пока лежит в инвентаре'
Фу
Фиговое описание

2016-09-27 06:53 UTC, yegorf1 commented on items/vietnam/ak.py
> +		user.remove_item('bullet')
Пусть будет не 10 выстрелов, а 30

2016-09-27 06:53 UTC, yegorf1 commented on items/vietnam/m-16.py
> +    'Почти не заржавела'
М16 пластиковая

2016-09-27 06:53 UTC, yegorf1 commented on items/vietnam/m-16.py
> +	while user.has_item('bullet') and res // 60 < 10:
Пусть стреляет 20 пуль, но по 30

2016-09-27 06:53 UTC, yegorf1 commented on items/vietnam/minigun.py
> +	while user.has_item('bullet') and res // 20 < 15:
40 патронов по 5

2016-09-27 06:53 UTC, yegorf1 commented on rooms/monster/vietnam/river.py
> +if user.has_item('m79'):
Этот код нужно перенести в `get_actions()`

2016-09-27 06:53 UTC, yegorf1 commented on rooms/monster/vietnam/river.py
> +                reply('Вы вспоминаете, что у вас есть М79, берёте его в руки гребёте им.')
Запятую или союз нужно (:

2016-09-27 06:53 UTC, yegorf1 commented on rooms/monster/vietnam/river.py
> +		if rvr > 8:
Переменной rvr нет, ты имел ввиду cnt

2016-09-27 06:53 UTC, yegorf1 commented on rooms/monster/vietnam/river.py
> +	reply('Дверь, через которую вы вошли, магическим образом исчезла.'
Здесь нет переносов строки (`/n`)

2016-09-27 06:53 UTC, yegorf1 commented on rooms/monster/vietnam/river.py
> +		cnt = user.get_room_temp('rvr', def_val=0)
Нужно инкременировать счетчик

2016-09-27 23:13 UTC, daemonica commented on items/vietnam/ak.py
> +		user.remove_item('bullet')
1800 с очереди? Ну как скажешь

2016-09-28 13:09 UTC, YogurtTheHorse approved these changes

2016-09-28 13:10 UTC, merged